エラーハンドリング
==========

Lumino は、実行されたメソッドが何らかの問題により目的を達成できない場合、エラーハンドラを実行することで問題を通知します。

既定のエラーハンドラは、エラーメッセージを表示した後、例外をスローします。


例外安全性
----------
Lumino は例外中立であり、例外安全の基本保証を満たすように設計されています。

メソッドの目的を達成できない問題は必ず通知し、関連するリソースを安全に開放します。


例外からのリカバリ
----------
Lumino のあるオブジェクト内から例外がスローされた場合、そのオブジェクトの内部状態の正当性は保証できないため、使用してはなりません。（オブジェクトの状態はロールバックされません）

必要に応じて前提条件を検証した後、オブジェクトを再構築します。


独自のエラーハンドラを使用する
----------
既定のエラーハンドラの動作をカスタマイズするには、`Exception::setNotificationHandler()` によって独自のエラーハンドラを登録します。

エラーハンドラが登録されている場合、既定のエラーハンドラは実行されません。

```cpp
bool myErrorHandler(Exception& e) {
    // エラーの記録などを行う

    // true を返すと、既定のエラーハンドラは実行されない
    return true;
}

int main() {
    Exception::setNotificationHandler(myErrorHandler);
    ・・・
}
```

また、独自のエラーハンドラはスレッドセーフで実装する必要があります。


例外を使用しないようにする
----------
Lumino の例外スローは 既定のエラーハンドラ に集約されているため、独自のエラーハンドラ内で例外をスローしなければ Lumino は例外をスローしなくなります。

例外をスローせずにエラーハンドラを終了すると Lumino は引き続き積極的に検証を行いながら、後続の処理を実行し続けます。








